version: 2

project_name: chaos-doctor

before:
  hooks:
    - go mod download

env:
  - CGO_ENABLED=0

builds:
  - main: ./doctor
    binary: doctor
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version=v{{.Version}}
