name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7.0.1

      - name: Install Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Setup GO env
        run: go env -w CGO_ENABLED=0

      - name: Format
        run: test -z "$(gofmt -l .)"

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -o bin/doctor ./cmd/doctor
